### ISSUE TITLE
Logo offer wifi-share

### ISSUE THREAD

**Issue by familqasimov** [thanosgn/wifi-share#1]
Hi Thanos Giannopoulos.
 
I'm designing for open source projects and I'm trying to expand my design tecnigue with these jobs. I want to design an icon for your project. I have a few ideas in my mind, I hope you accept and I do them. Please let me know if you have any ideas. In this way, we create a logo that will make you happy.
If you want, you can look at my repositories.
https://github.com/familqasimov?tab=overview&from=2018-06-01&to=2018-06-30

Best regards.
Famil

**Comment by thanosgn** [comment]
Hi Famil,

Your work seems pretty cool!

My idea for the project logo was to somewhat combine the QR logo with the WiFi one as you can see [here](https://camo.githubusercontent.com/82ceadbdf693f2ef6d12651a6648b4d88cff0a06/68747470733a2f2f7468616e6f73676e2e6769746875622e696f2f6173736574732f71722d776966692e737667).

I would love to see your ideas too. I am sure we will find something nice.
You can contact me by email to discuss.

Best,
Thanos

**Comment by familqasimov** [comment]
![untitled-1](https://user-images.githubusercontent.com/36432269/43690195-feb5cc6c-9916-11e8-945c-b25e1908bb19.png)

**Comment by thanosgn** [comment]
Nice job!

I like the second design very much, but I would love it if it also had the QR element.

Do you think that a QR background would suit it?

Thanks a lot,
Thanos

**Comment by familqasimov** [comment]
I also think like you. The second design looks simple and minimalist. The simplicity of the logo looks more attractive. Can I send you a PR if you like it?

**Comment by thanosgn** [comment]
I also like the minimalist but I think it should include something about a QR code. What do you think?

I think something in between the 2 samples that you designed would be the best.

**Comment by thanosgn** [comment]
Maybe an idea would be that the WiFi logo in the second one would look something like [this](https://camo.githubusercontent.com/82ceadbdf693f2ef6d12651a6648b4d88cff0a06/68747470733a2f2f7468616e6f73676e2e6769746875622e696f2f6173736574732f71722d776966692e737667)?

**Comment by familqasimov** [comment]
I think the QR code inside the logo does not give a complete idea as to what it is not clear.

Maybe one of them may well.

![untitled-2](https://user-images.githubusercontent.com/36432269/43731608-1485d2d6-99c0-11e8-9ecc-533ac2607723.png)

**Comment by thanosgn** [comment]
Nice!

I like the second image the most.

Can you create a PR with the second image as an .svg?

Many thanks

**Comment by thanosgn** [comment]
Your PR is merged. Thanks!

**Comment by familqasimov** [comment]
I thank you. Always good luck ...

Thanos Giannopoulos <notifications@github.com>, 7 Ağu 2018 Sal, 22:02
tarihinde şunu yazdı:
