### ISSUE TITLE
Error getting Wi-Fi password

### ISSUE THREAD

**Issue by jkirk** [thanosgn/wifi-share#4]
Hi,

Running `wifi-share` (via sudo) returns:
```
[-] Error getting Wi-Fi password
```

After a little bit of debugging it turned out that NetworkManager on my system (Debian/stretch with network-manager 1.6.2-3+deb9u2) saves the connections in the file `Auto $ESSID` which causes the line of subject to fail:
https://github.com/thanosgn/wifi-share/blob/15488ec95e8747728f64ac4106a6541dc694720d/wifi-share.py#L173

My workaround looks like this:
```
% git diff
diff --git a/wifi-share.py b/wifi-share.py
index 7445e64..366326a 100755
--- a/wifi-share.py
+++ b/wifi-share.py
@@ -170,7 +170,7 @@ def main():
                 if wifi_name == None:
                     raise ProcessError
             else:
-                with open( os.path.join('/etc/NetworkManager/system-connections', wifi_name), 'r') as network_file:
+                with open( os.path.join('/etc/NetworkManager/system-connections', 'Auto ' + wifi_name), 'r') as network_file:
                     for line in network_file:
                         if 'psk=' in line:
                             wifi_password = line.split('=')[1].rstrip('\r\n')
```

I wonder what the "best" fix would look like. The system connection file does not necessarily needs to be `wifi_name` or even `Auto wifi_name`. Maybe we should grep for the SSID in every file instead?

**Comment by thanosgn** [comment]
Thanks a lot for the feedback.

I had only see `wifi_name` as a filename with any OS/NetworkManager configuration so far.

`grep`-ing seems a reasonable solution, given the circumstances, even as a backup plan, if the original guess for the filename fails.

I will have a look at it these days.

**Comment by thanosgn** [comment]
Hi Darshaka,

I changed the way of accessing saved connection information.
I was unaware of the `nmcli` utility which is very handy and is what is used now by `wifi-share`.

Bonus: `wifi-share` does not need `root` access anymore!

Now the program should work for any system configuration that uses NetworkManager.

Could you please verify that it also works for you now so I can close the issue?

**Comment by jkirk** [comment]
Hey Thanos!

Thank you very much for the feedback and your efforts to fix this issue!

Just tried your update and I do not get the _Error getting Wi-Fi password_ message anymore but this is what I get:

```sh
% sudo venv/bin/python wifi-share.py --verbose
[sudo] password for jkirk:
[~] Running: iwgetid -r
[+] You are connected to home.example.com Wi-Fi
[~] Running: nmcli connection show id home.example.com --show-secrets
[~] Running: grep 802-11-wireless-security.psk:
[~] Running: awk {print $2}
[!] No password needed for this network.
[QRCODE SNIPPED]
```

So the issues are:
* _No password needed for this network._ is wrong
* Sudo / root is still needed (because of `iwgetid`)

I'll try to debug a little more and come back if have more infos.

**Comment by thanosgn** [comment]
Hello again,

First of all, thanks for the feedback you provide.

Second, are you sure about `iwgetid` needing root permissions? On Ubuntu at least it does not.

Also, if you would like, you could post / send privately the output of `nmcli connection show id home.example.com --show-secrets` (probably you would want to replace your actual password with a dummy one if it is present in the output) so I can debug this too.

**Comment by jkirk** [comment]
Hey...

I missed your comment, while working on this.. sorry! I just created a PR with my findings / proposal. Please tell me what you think.

Regarding: iwgetid(8). I justed tested it and you were right, iwgetid does not need root permissions. But it is in /sbin and not in PATH that's why I assumed root permissions. (Maybe this is a bug and the program should be installed to /usr/bin? I will have to talk to the wireless-tools maintainers.)
Still, iwgetid is assumed to be in the search path which is not the case on my system. What is the best way to handle that?

**Comment by thanosgn** [comment]
Probably the best way is to use `nmcli` for getting this info also. 

It removes one dependency.
